Add Addons
openactive/ns-beta pull request #29
Opened 2021-11-11 13:36 UTC by nathansalter

Adds addons as related to https://github.com/openactive/modelling-opportunity-data/issues/297

2021-11-11 14:37 UTC, nickevansuk requested changes
A few quick notes on this PR. Can certainly add more explanation if that's helpful, let me know!

Note the difference between classes and properties from this example:

```
"beta:availableQuantity": {
  "@type": "QuantitiveValue",
  "minValue": 0,
  "maxValue": 4
},
```

`beta:availableQuantity` is the Property
`QuantitiveValue` is the Class

Hope this helps!

2021-11-11 14:37 UTC, nickevansuk commented on beta.jsonld
> +    },
This seems to be a mix of a Class (e.g. [here](https://github.com/openactive/ns-beta/blob/3bdc175d51e8bd9bca27e142f3fc0929209dcf12/beta.jsonld#L115-L125)) and a Property (e.g. [here](https://github.com/openactive/ns-beta/blob/3bdc175d51e8bd9bca27e142f3fc0929209dcf12/beta.jsonld#L102-L114)).

Note that terms are case sensitive, so if this is a class ("Addon") it would be different to a property ("addOn").

2021-11-11 14:37 UTC, nickevansuk commented on beta.jsonld
> +      ],
This is missing a range

2021-11-11 14:37 UTC, nickevansuk commented on beta.jsonld
> +      "@type": "Class",
This is a Property rather than a Class

2021-12-07 15:19 UTC, nickevansuk requested changes
A few more comments here - probably shows we need better documentation for the format here

2021-12-07 15:19 UTC, nickevansuk commented on beta.jsonld
> +      "domainIncludes": [
Seems to be missing a `rangeIncludes`?

2021-12-07 15:19 UTC, nickevansuk commented on beta.jsonld
> +      "domainIncludes": [
Seems to be missing a `rangeIncludes`?

2021-12-07 15:19 UTC, nickevansuk commented on beta.jsonld
> +      "@container": "@list",
```suggestion
```

`"@container": "@list",` only indicates whether a _property_ is an array, so is not relevant on a class

2021-12-07 15:19 UTC, nickevansuk commented on beta.jsonld
> +      "label": "AvailableQuantity",
```suggestion
      "label": "availableQuantity",
```

Always lower case first letter for properties

2021-12-15 17:05 UTC, nathansalter commented on beta.jsonld
> +      "domainIncludes": [
Yeah I wasn't quite sure what this was supposed to be

2021-12-17 11:57 UTC, nickevansuk requested changes
Pretty close now!

Though reviewing the model as a whole I wonder whether we've missed something around P/B, see: https://github.com/openactive/modelling-opportunity-data/issues/297#issuecomment-996666349

2021-12-17 11:57 UTC, nickevansuk commented on beta.jsonld
> +      ],
Properties don't have subclasses

2021-12-17 11:57 UTC, nickevansuk commented on beta.jsonld
> +        "oa:OrderItem"
```suggestion
        "schema:OrderItem"
```

You can easily check to see which namespace a term is in by replacing the prefix with the URL, e.g.
- https://openactive.io/OrderItem
- https://schema.org/OrderItem

The one that doesn't return a 404 is where the term lives

2022-01-13 11:39 UTC, nathansalter commented
> Pretty close now!
> 
> Though reviewing the model as a whole I wonder whether we've missed something around P/B, see: [openactive/modelling-opportunity-data#297 (comment)](https://github.com/openactive/modelling-opportunity-data/issues/297#issuecomment-996666349)

Yeah, I've updated the data models with this new property

2022-01-13 15:35 UTC, nickevansuk requested changes

2022-01-13 15:35 UTC, nickevansuk commented on beta.jsonld
> +    },
Do we still need this?

2022-01-13 15:36 UTC, nathansalter commented on beta.jsonld
> +    },
Nope!

2026-05-13 13:52 UTC, closed without merging